//! Layout application: apply_layout, its phase helpers, and animation frame dispatch.

use crate::animation_worker;
use crate::state::*;
use anyhow::{anyhow, Result};
use std::collections::HashMap;
use std::sync::atomic::Ordering;
use tracing::{debug, warn};

const MAX_TIMEOUT_DIAGNOSTIC_CHARS: usize = 256;

fn effective_column_widths(
    workspace: &leopardwm_core_layout::Workspace,
) -> impl Iterator<Item = i32> + '_ {
    workspace
        .columns()
        .iter()
        .map(|column| workspace.effective_column_width(column))
}

pub(crate) fn should_dispatch_visible_tiled_placement(
    maximized: bool,
    settling: bool,
    placement_parked: bool,
) -> bool {
    !settling && (!maximized || placement_parked)
}

fn bounded_timeout_diagnostic(value: String) -> Option<String> {
    if value.is_empty() {
        return None;
    }

    let mut chars = value.chars();
    let mut bounded: String = chars.by_ref().take(MAX_TIMEOUT_DIAGNOSTIC_CHARS).collect();
    if chars.next().is_some() {
        bounded.push('…');
    }
    Some(bounded)
}

fn run_layout_apply_recovery_pass(window_ids: &[u64], context: &str) {
    #[cfg(not(test))]
    run_visibility_recovery_pass(window_ids, context);
    #[cfg(test)]
    let _ = (window_ids, context);
}

/// Message sent back from the apply-layout worker thread.
type ApplyWorkerMsg = (
    Result<()>,
    Vec<leopardwm_platform_win32::WidthViolation>,
    Vec<leopardwm_platform_win32::HeightViolation>,
    Vec<u64>,
    Vec<leopardwm_platform_win32::PlacementLanding>,
);

pub(crate) enum AnimationPlacementResult {
    Current,
    InvalidatedCurrent,
    Stale,
}

impl AppState {
    /// Record a short suppression window for moved/resized feedback generated by apply_layout().
    pub(crate) fn arm_moved_or_resized_suppression<I>(&mut self, window_ids: I)
    where
        I: IntoIterator<Item = u64>,
    {
        let now = std::time::Instant::now();
        self.moved_or_resized_suppression
            .retain(|_, deadline| *deadline > now);
        let deadline = now + MOVED_OR_RESIZED_SUPPRESSION_WINDOW;
        for hwnd in window_ids {
            self.moved_or_resized_suppression.insert(hwnd, deadline);
        }
    }

    /// Returns true when a moved/resized event should be ignored due to recent apply_layout().
    pub(crate) fn should_suppress_moved_or_resized(&mut self, hwnd: u64) -> bool {
        let now = std::time::Instant::now();
        self.moved_or_resized_suppression
            .retain(|_, deadline| *deadline > now);
        self.moved_or_resized_suppression
            .get(&hwnd)
            .is_some_and(|deadline| *deadline > now)
    }

    pub(crate) fn handle_maximized_placement_skips(&mut self, window_ids: &[u64]) {
        for window_id in window_ids {
            self.moved_or_resized_suppression.remove(window_id);
            self.last_placed_layout_rects.remove(window_id);
        }
        self.record_maximized_observations(&window_ids.iter().copied().collect());
    }

    pub(crate) fn handle_animation_placement_result(
        &mut self,
        frame_result: &animation_worker::FrameResult,
    ) -> AnimationPlacementResult {
        if self.animation_inflight_request_id == Some(frame_result.physical_request_id) {
            self.animation_inflight_request_id = None;
        }
        if !self.physical_result_matches_inflight(
            frame_result.physical_request_id,
            frame_result.physical_invalidation_id,
        ) {
            debug!(
                request_id = frame_result.physical_request_id,
                invalidation_id = frame_result.physical_invalidation_id,
                "Ignoring stale animation placement result"
            );
            return AnimationPlacementResult::Stale;
        }
        if !self.physical_result_is_current(
            frame_result.physical_request_id,
            frame_result.physical_invalidation_id,
        ) {
            if self.inflight_request_id == Some(frame_result.physical_request_id) {
                self.inflight_request_id = None;
                self.inflight_origins
                    .remove(&frame_result.physical_request_id);
            }
            self.applying_layout = false;
            return AnimationPlacementResult::InvalidatedCurrent;
        }

        let width_violations: Vec<_> = frame_result
            .width_violations
            .iter()
            .filter(|violation| {
                self.allows_core_size_feedback(
                    frame_result.physical_request_id,
                    violation.window_id,
                )
            })
            .cloned()
            .collect();
        let height_violations: Vec<_> = frame_result
            .height_violations
            .iter()
            .filter(|violation| {
                self.allows_core_size_feedback(
                    frame_result.physical_request_id,
                    violation.window_id,
                )
            })
            .cloned()
            .collect();

        self.applying_layout = false;
        self.handle_maximized_placement_skips(&frame_result.maximized_skipped_window_ids);
        if !frame_result.landings.is_empty() {
            self.consume_physical_landings(
                frame_result.physical_request_id,
                frame_result.physical_invalidation_id,
                &frame_result.landings,
            );
        }
        if frame_result.apply_result.is_ok() {
            self.propagate_size_violations(&width_violations, &height_violations);
        }
        AnimationPlacementResult::Current
    }

    fn observe_maximized_placements(
        &mut self,
        placements: &[leopardwm_core_layout::WindowPlacement],
    ) -> std::collections::HashSet<u64> {
        let maximized: std::collections::HashSet<u64> = placements
            .iter()
            .filter(|placement| {
                placement.visibility == leopardwm_core_layout::Visibility::Visible
                    && placement.column_index != usize::MAX
                    && leopardwm_platform_win32::is_window_maximized(placement.window_id)
            })
            .map(|placement| placement.window_id)
            .collect();
        self.record_maximized_observations(&maximized);
        maximized
    }

    pub(crate) fn record_maximized_observations(
        &mut self,
        maximized: &std::collections::HashSet<u64>,
    ) {
        let now = std::time::Instant::now();
        for hwnd in maximized {
            self.window_last_maximized_at.insert(*hwnd, now);
            self.stop_ghosting_window_visuals(*hwnd);
        }
    }

    pub(crate) fn observe_tiled_window_maximized(&mut self, hwnd: u64) {
        self.record_maximized_observations(&std::collections::HashSet::from([hwnd]));
    }

    fn prepare_physical_placements(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
    ) -> Vec<leopardwm_core_layout::WindowPlacement> {
        let maximized = self.observe_maximized_placements(&placements);
        self.prepare_physical_placements_with_parked(
            placements,
            &maximized,
            leopardwm_platform_win32::is_placement_parked,
        )
    }

    pub(crate) fn prepare_physical_placements_with_parked<F>(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
        maximized: &std::collections::HashSet<u64>,
        is_placement_parked: F,
    ) -> Vec<leopardwm_core_layout::WindowPlacement>
    where
        F: Fn(u64) -> bool,
    {
        let placements =
            self.filter_physical_placements_with_parked(placements, maximized, is_placement_parked);
        self.apply_physical_projection(placements)
    }

    #[cfg(test)]
    pub(crate) fn filter_physical_placements_observed(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
        maximized: &std::collections::HashSet<u64>,
    ) -> Vec<leopardwm_core_layout::WindowPlacement> {
        self.filter_physical_placements_with_parked(
            placements,
            maximized,
            leopardwm_platform_win32::is_placement_parked,
        )
    }

    fn filter_physical_placements_with_parked<F>(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
        maximized: &std::collections::HashSet<u64>,
        is_placement_parked: F,
    ) -> Vec<leopardwm_core_layout::WindowPlacement>
    where
        F: Fn(u64) -> bool,
    {
        let now = std::time::Instant::now();
        placements
            .into_iter()
            .filter(|placement| {
                if placement.visibility != leopardwm_core_layout::Visibility::Visible
                    || placement.column_index == usize::MAX
                {
                    return true;
                }
                let settling = crate::event_handler::defer_snapback_while_settling(
                    self.window_managed_at.get(&placement.window_id).copied(),
                    self.window_last_maximized_at
                        .get(&placement.window_id)
                        .copied(),
                    now,
                );
                let maximized = maximized.contains(&placement.window_id);
                if !should_dispatch_visible_tiled_placement(
                    maximized,
                    settling,
                    is_placement_parked(placement.window_id),
                ) {
                    return false;
                }
                self.window_last_maximized_at.remove(&placement.window_id);
                true
            })
            .collect()
    }

    #[cfg(test)]
    pub(crate) fn prepare_animation_frame(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
        maximized: &std::collections::HashSet<u64>,
    ) -> animation_worker::FrameRequest {
        self.prepare_animation_frame_with_parked(
            placements,
            maximized,
            leopardwm_platform_win32::is_placement_parked,
        )
    }

    #[cfg(test)]
    pub(crate) fn prepare_animation_frame_with_parked<F>(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
        maximized: &std::collections::HashSet<u64>,
        is_placement_parked: F,
    ) -> animation_worker::FrameRequest
    where
        F: Fn(u64) -> bool,
    {
        let placements =
            self.filter_physical_placements_with_parked(placements, maximized, is_placement_parked);
        self.prepare_projected_animation_frame(placements)
    }

    fn prepare_projected_animation_frame(
        &mut self,
        placements: Vec<leopardwm_core_layout::WindowPlacement>,
    ) -> animation_worker::FrameRequest {
        let (live_placements, ghost_updates) = Self::partition_for_animation(
            placements,
            self.layout_transition.as_ref(),
            &self.ghost_handles,
        );
        self.arm_moved_or_resized_suppression(
            live_placements.iter().map(|placement| placement.window_id),
        );
        let (physical_request_id, physical_invalidation_id) = self.physical_request_ids();
        animation_worker::FrameRequest {
            placements: live_placements,
            ghost_updates,
            platform_config: self.platform_config.clone(),
            physical_request_id,
            physical_invalidation_id,
            physical_dispatch_request_id: self.physical_dispatch_request_id.clone(),
            physical_invalidation: self.physical_invalidation_id.clone(),
        }
    }

    /// Join any finished timed-out apply workers so the pending list does not grow indefinitely.
    /// Returns the number of workers reaped in this pass.
    pub(crate) fn reap_finished_pending_apply_workers(&mut self) -> usize {
        if self.pending_apply_workers.is_empty() {
            return 0;
        }
        let mut still_running = Vec::with_capacity(self.pending_apply_workers.len());
        let mut reaped = 0usize;
        for handle in self.pending_apply_workers.drain(..) {
            if handle.is_finished() {
                let _ = handle.join();
                reaped += 1;
            } else {
                still_running.push(handle);
            }
        }
        self.pending_apply_workers = still_running;
        reaped
    }

    /// Mark shutdown/revert in progress and take ownership of any timed-out apply workers.
    pub(crate) fn begin_shutdown_or_revert(&mut self) -> Vec<std::thread::JoinHandle<()>> {
        self.apply_worker_cancelled.store(true, Ordering::SeqCst);
        self.apply_epoch.fetch_add(1, Ordering::SeqCst);
        std::mem::take(&mut self.pending_apply_workers)
    }

    /// Compute animated placements and send them to the animation worker.
    ///
    /// Returns `Ok(true)` if a frame was sent, `Ok(false)` if paused or no placements.
    pub(crate) fn send_animation_frame(
        &mut self,
        worker: &animation_worker::AnimationWorkerHandle,
    ) -> Result<bool> {
        if self.paused {
            return Ok(false);
        }
        // Gate after console-signal / shutdown latch so we never compute or
        // dispatch a frame that would re-park windows after restore.
        if self.apply_worker_cancelled.load(Ordering::SeqCst) {
            return Ok(false);
        }
        // Commit deferred min-size clears before the frame reads constraints,
        // matching the invariant maintained by apply_layout. Without this, a
        // composition change occurring during an active animation would leave
        // stale per-sibling constraints in effect for the remaining frames.
        self.commit_pending_min_size_clears();
        let mut all_placements = Vec::new();
        for (monitor_id, ws_vec) in &self.workspaces {
            let idx = self.active_workspace_idx(*monitor_id);
            if let Some(workspace) = ws_vec.get(idx) {
                if self.monitors.contains_key(monitor_id) {
                    let viewport = self.layout_viewport(*monitor_id);
                    let mut placements = workspace.compute_placements_animated(viewport);
                    crate::physical_placement::park_offscreen_avoiding_neighbors(
                        &mut placements,
                        *monitor_id,
                        &self.monitors,
                    );
                    all_placements.extend(placements);
                }
            }
        }
        if all_placements.is_empty()
            && self
                .layout_transition
                .as_ref()
                .is_none_or(|t| t.exit_rects.is_empty())
        {
            return Ok(false);
        }

        // Interpolate layout transitions (structural changes like move/expel).
        if let Some(ref transition) = self.layout_transition {
            Self::apply_transition_interpolation(transition, &mut all_placements);
        }

        // Filter out the dragged window and placeholder so SetWindowPos doesn't
        // fight the OS drag or try to position the sentinel.
        if let Some(ref drag) = self.drag_state {
            if drag.is_tiled {
                all_placements.retain(|p| {
                    p.window_id != drag.hwnd && p.window_id != crate::state::DRAG_PLACEHOLDER_HWND
                });
            }
        }

        let dispatched_placements = self.filter_application_fullscreen_placements(all_placements);
        let maximized = self.observe_maximized_placements(&dispatched_placements);
        let dispatched_placements = self.filter_physical_placements_with_parked(
            dispatched_placements,
            &maximized,
            leopardwm_platform_win32::is_placement_parked,
        );
        self.animation_inflight_request_id = None;
        let dispatched_placements = self.apply_physical_projection(dispatched_placements);

        // Partition into live placements + ghost-thumbnail updates. Ghost
        // wids are excluded from `placements` so the worker doesn't fire
        // per-frame SetWindowPos on the cloaked source HWND.
        let request = self.prepare_projected_animation_frame(dispatched_placements);
        let (request_id, invalidation_id) = (
            request.physical_request_id,
            request.physical_invalidation_id,
        );
        self.applying_layout = true;

        if let Err(e) = worker.send_frame(request) {
            self.abandon_physical_request(request_id, invalidation_id);
            self.applying_layout = false;
            return Err(anyhow::anyhow!(e));
        }
        self.animation_inflight_request_id = Some(request_id);
        // Reposition the border immediately — both the worker's
        // SetWindowPos calls below and this border SetWindowPos commit
        // before the next DwmFlush vsync, so the border arrives on screen
        // in the same frame as the windows. Without this the FIRST
        // animation frame paints with the stale border position, since
        // the post-frame `tick + show_border` reorder in `main.rs` only
        // fires for frames 2+ (frame 1's `AnimationFrameApplied` arrives
        // AFTER frame 1 has already been presented).
        if let Some(hwnd) = self.previous_focused_hwnd {
            if self.config.appearance.active_border {
                self.show_border(hwnd);
            }
        }
        self.update_tab_strip();
        Ok(true)
    }

    fn collect_layout_apply_timeout_candidates(
        &self,
        window_ids: &[u64],
    ) -> Vec<LayoutApplyTimeoutCandidate> {
        let mut executable_by_pid: HashMap<u32, Option<String>> = HashMap::new();

        window_ids
            .iter()
            .map(|&hwnd| {
                let Some(info) = self.lookup_window_info(hwnd) else {
                    return LayoutApplyTimeoutCandidate {
                        hwnd,
                        class_name: None,
                        title: None,
                        executable: None,
                    };
                };
                let executable = executable_by_pid
                    .entry(info.process_id)
                    .or_insert_with(|| {
                        leopardwm_platform_win32::get_process_executable(info.process_id)
                    })
                    .clone()
                    .and_then(bounded_timeout_diagnostic);

                LayoutApplyTimeoutCandidate {
                    hwnd,
                    class_name: bounded_timeout_diagnostic(info.class_name),
                    title: bounded_timeout_diagnostic(info.title),
                    executable,
                }
            })
            .collect()
    }

    /// Recalculate layout and apply placements for all monitors.
    /// Uses animated offsets if any workspace has an active animation.
    /// No-op when tiling is paused.
    pub(crate) fn apply_layout(&mut self) -> Result<()> {
        let reaped_workers = self.reap_finished_pending_apply_workers();
        if reaped_workers > 0 {
            let managed_window_ids = self.all_managed_window_ids();
            run_layout_apply_recovery_pass(&managed_window_ids, "late-apply-worker");
        }

        if self.paused {
            return Ok(());
        }
        // During layout transitions, the animation worker drives positioning.
        if self.layout_transition.is_some() {
            return Ok(());
        }
        if self.apply_worker_cancelled.load(Ordering::SeqCst) {
            return Err(anyhow!(
                "Layout application skipped: shutdown/revert cleanup is in progress"
            ));
        }
        if !self.pending_apply_workers.is_empty() {
            return Err(anyhow!(
                "Layout application skipped: previous timed-out apply worker is still finishing"
            ));
        }
        self.retain_application_fullscreen_sessions();
        self.applying_layout = true;

        // Commit any deferred min-size constraint clears scheduled by
        // composition changes (add_window / insert_at / remove_window). Done
        // here rather than eagerly at the mutation site so that a timed-out /
        // paused apply path cannot leave constraints cleared indefinitely.
        self.commit_pending_min_size_clears();

        let mut all_placements = self.collect_apply_placements();
        let logically_empty = all_placements.is_empty();

        // Interpolate layout transitions (structural changes like move/expel).
        if let Some(ref transition) = self.layout_transition {
            Self::apply_transition_interpolation(transition, &mut all_placements);
        }

        // Filter out the dragged window and placeholder so SetWindowPos doesn't
        // fight the OS drag or try to position the sentinel.
        if let Some(ref drag) = self.drag_state {
            if drag.is_tiled {
                all_placements.retain(|p| {
                    p.window_id != drag.hwnd && p.window_id != crate::state::DRAG_PLACEHOLDER_HWND
                });
            }
        }

        // Fast path: unchanged placements and visible-set need no worker
        // unless a post-animation landing is pending. Spawning
        // the worker thread, the BeginDeferWindowPos batch, the DwmFlush,
        // size-violation queries, and the sticky-compositor nudge each take
        // tens of milliseconds; under rapid focus presses within the
        // already-visible range no scroll animation starts (so the caller
        // does not get to bypass us via `is_animating()`) and these calls
        // serialize on the daemon mutex, leaving focus events draining for
        // seconds after the user stops pressing. Returning early lets the
        // event loop catch up at near-memory speed.
        let placements_unchanged = self.placements_match_last_applied(&all_placements);
        // Tests that inject worker behavior need the worker to actually
        // run, so they opt out of the fast path.
        #[cfg(test)]
        let bypass_fast_path = self.injected_apply_placements_behavior.is_some();
        #[cfg(not(test))]
        let bypass_fast_path = false;
        if placements_unchanged
            && self.physical_fast_path_ok()
            && !self.post_animation_nudge_pending
            && !bypass_fast_path
        {
            self.applying_layout = false;
            self.request_save_if_changed();
            return Ok(());
        }

        self.record_last_placed_rects(&all_placements);
        let dispatched_placements = self.filter_application_fullscreen_placements(all_placements);
        self.animation_inflight_request_id = None;
        let dispatched_placements = self.prepare_physical_placements(dispatched_placements);
        let (physical_request_id, physical_invalidation_id) = self.physical_request_ids();
        #[cfg(test)]
        let invoke_injected_empty_worker =
            self.injected_apply_placements_behavior.is_some() && dispatched_placements.is_empty();
        #[cfg(not(test))]
        let invoke_injected_empty_worker = false;
        if dispatched_placements.is_empty() && !invoke_injected_empty_worker {
            self.acknowledge_empty_physical_state(
                physical_request_id,
                physical_invalidation_id,
                logically_empty,
            );
            self.abandon_physical_request(physical_request_id, physical_invalidation_id);
            self.applying_layout = false;
            self.finalize_layout_success();
            return Ok(());
        }

        let timeout_candidate_ids: Vec<u64> = dispatched_placements
            .iter()
            .map(|placement| placement.window_id)
            .collect();

        self.arm_moved_or_resized_suppression(
            dispatched_placements
                .iter()
                .map(|placement| placement.window_id),
        );

        let timeout = self.layout_apply_timeout;
        let (rx, worker_handle) = match self.spawn_apply_worker(dispatched_placements) {
            Ok(worker) => worker,
            Err(error) => {
                self.abandon_physical_request(physical_request_id, physical_invalidation_id);
                self.applying_layout = false;
                return Err(error);
            }
        };

        let result = match rx.recv_timeout(timeout) {
            Ok((
                result,
                width_violations,
                height_violations,
                maximized_skipped_window_ids,
                landings,
            )) => {
                let _ = worker_handle.join();
                let width_violations: Vec<_> = width_violations
                    .into_iter()
                    .filter(|violation| {
                        self.allows_core_size_feedback(physical_request_id, violation.window_id)
                    })
                    .collect();
                let height_violations: Vec<_> = height_violations
                    .into_iter()
                    .filter(|violation| {
                        self.allows_core_size_feedback(physical_request_id, violation.window_id)
                    })
                    .collect();
                let primary_succeeded = result.is_ok();
                let result = if result.is_err() {
                    self.moved_or_resized_suppression.clear();
                    self.abandon_physical_request(physical_request_id, physical_invalidation_id);
                    result
                } else {
                    self.handle_maximized_placement_skips(&maximized_skipped_window_ids);
                    self.consume_physical_landings(
                        physical_request_id,
                        physical_invalidation_id,
                        &landings,
                    );
                    Ok(())
                };
                let constraints_changed = primary_succeeded
                    && self.propagate_size_violations(&width_violations, &height_violations);
                let restored_during_apply = result.is_ok()
                    && maximized_skipped_window_ids.iter().any(|window_id| {
                        !leopardwm_platform_win32::is_window_maximized(*window_id)
                            && !crate::event_handler::defer_snapback_while_settling(
                                self.window_managed_at.get(window_id).copied(),
                                self.window_last_maximized_at.get(window_id).copied(),
                                std::time::Instant::now(),
                            )
                    });
                // If any constraint was added, run a single guarded re-apply
                // so the corrected layout lands on the current frame instead
                // of waiting for the next user-triggered event. The inner
                // apply_layout manages its own applying_layout state; we just
                // need to release our own first so the guard at the top of
                // the recursive call can re-enter cleanly. If the inner call
                // fails (e.g. its worker times out and pauses the daemon), we
                // surface that error in place of the outer Ok — the outer
                // placements may have already landed, but the daemon state
                // needs to reflect that the corrective pass didn't complete.
                if result.is_ok()
                    && (constraints_changed || restored_during_apply)
                    && !self.reapplying_after_violation
                {
                    self.reapplying_after_violation = true;
                    self.applying_layout = false;
                    let reapply = self.apply_layout();
                    self.reapplying_after_violation = false;
                    if let Err(e) = reapply {
                        warn!("Re-apply after size-violation propagation failed: {}", e);
                        Err(e)
                    } else {
                        result
                    }
                } else {
                    result
                }
            }
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                self.abandon_physical_request(physical_request_id, physical_invalidation_id);
                self.paused = true;
                // Invalidate this apply epoch so late-starting workers bail before placement calls.
                self.apply_epoch.fetch_add(1, Ordering::SeqCst);
                self.pending_apply_workers.push(worker_handle);
                self.moved_or_resized_suppression.clear();
                let msg = layout_apply_timeout_message(timeout);
                let report = LayoutApplyTimeoutReport {
                    timeout,
                    candidates: self
                        .collect_layout_apply_timeout_candidates(&timeout_candidate_ids),
                };
                warn!(
                    "{} Timed-out placement batch contained {} candidate window(s); batch membership does not prove which window blocked placement.",
                    msg,
                    report.candidates.len()
                );
                for candidate in &report.candidates {
                    warn!(
                        "Timed-out placement batch candidate (not a proven blocker): hwnd={:#x} class={:?} title={:?} executable={:?}",
                        candidate.hwnd,
                        candidate.class_name,
                        candidate.title,
                        candidate.executable
                    );
                }
                self.pending_layout_apply_timeout_report = Some(report);
                let managed_window_ids = self.all_managed_window_ids();
                run_layout_apply_recovery_pass(&managed_window_ids, "apply-timeout");
                Err(anyhow!(msg))
            }
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                let _ = worker_handle.join();
                self.abandon_physical_request(physical_request_id, physical_invalidation_id);
                self.moved_or_resized_suppression.clear();
                Err(anyhow!(
                    "Layout worker thread exited without returning a result"
                ))
            }
        };
        self.applying_layout = false;

        // Reposition border to track the focused window after layout changes.
        // A thumbnail-revoked source remains cloaked until this exact landing
        // is current, confirmed, and not parked.
        if result.is_ok() {
            self.release_ghost_sources_after_physical_landing();
            self.finalize_layout_success();
        }

        result
    }

    /// Collect animated placements for every monitor's active workspace, with debug logging.
    fn collect_apply_placements(&self) -> Vec<leopardwm_core_layout::WindowPlacement> {
        let mut all_placements = Vec::new();

        for (monitor_id, ws_vec) in &self.workspaces {
            let idx = self.active_workspace_idx(*monitor_id);
            if let Some(workspace) = ws_vec.get(idx) {
                if self.monitors.contains_key(monitor_id) {
                    // Use animated placements to support smooth scrolling
                    let viewport = self.layout_viewport(*monitor_id);
                    let mut placements = workspace.compute_placements_animated(viewport);
                    crate::physical_placement::park_offscreen_avoiding_neighbors(
                        &mut placements,
                        *monitor_id,
                        &self.monitors,
                    );
                    debug!(
                        "Monitor {}: {} placements for viewport {}x{} (animating: {}, scroll: {:.1}, minimized: {})",
                        monitor_id,
                        placements.len(),
                        viewport.width,
                        viewport.height,
                        workspace.is_animating(),
                        workspace.effective_scroll_offset(),
                        workspace.minimized_count()
                    );
                    for p in &placements {
                        if p.visibility == leopardwm_core_layout::Visibility::Visible {
                            debug!(
                                "  placement hwnd={:#x} col={} rect=({},{} {}x{}) vis={:?}",
                                p.window_id,
                                p.column_index,
                                p.rect.x,
                                p.rect.y,
                                p.rect.width,
                                p.rect.height,
                                p.visibility,
                            );
                        }
                    }
                    all_placements.extend(placements);
                }
            }
        }

        all_placements
    }

    /// Fast-path check: every placement matches the last applied rect and the visible-set is unchanged.
    fn placements_match_last_applied(
        &self,
        all_placements: &[leopardwm_core_layout::WindowPlacement],
    ) -> bool {
        all_placements.iter().all(|p| {
            let expected = self.last_placed_layout_rects.get(&p.window_id);
            match p.visibility {
                leopardwm_core_layout::Visibility::Visible => expected == Some(&p.rect),
                _ => expected.is_none(),
            }
        }) && {
            let current_ids: std::collections::HashSet<u64> =
                all_placements.iter().map(|p| p.window_id).collect();
            !self
                .last_placed_layout_rects
                .keys()
                .any(|id| !current_ids.contains(id))
        }
    }

    /// Record layout rects for visible placements and drain stale entries.
    pub(crate) fn record_last_placed_rects(
        &mut self,
        all_placements: &[leopardwm_core_layout::WindowPlacement],
    ) {
        // Record the layout rect the engine chose for each window so the
        // MovedOrResized handler can short-circuit false-positive snap-backs
        // when Windows fires EVENT_OBJECT_LOCATIONCHANGE without an actual
        // position change. Visibility::Visible placements only — off-screen
        // parked windows aren't at their "layout" rect by design.
        //
        // Drain stale entries for windows that are no longer in the active
        // layout (workspace-switch leaves their hwnds alive but they stop
        // appearing in `all_placements`, which `apply_layout` builds from
        // active workspaces only). Without this drain the fast-path's
        // "no extra entries" guard fails forever after the first
        // Ctrl+Alt+1-9 — silently nullifying the rapid-Ctrl+Alt+Right/Left
        // perf fix for every multi-workspace user.
        let active_ids: std::collections::HashSet<u64> =
            all_placements.iter().map(|p| p.window_id).collect();
        self.last_placed_layout_rects
            .retain(|id, _| active_ids.contains(id));
        for p in all_placements {
            if matches!(p.visibility, leopardwm_core_layout::Visibility::Visible) {
                self.last_placed_layout_rects.insert(p.window_id, p.rect);
            } else {
                self.last_placed_layout_rects.remove(&p.window_id);
            }
        }
    }

    /// Spawn the apply-layout worker thread; returns its result channel and join handle.
    fn spawn_apply_worker(
        &mut self,
        all_placements: Vec<leopardwm_core_layout::WindowPlacement>,
    ) -> Result<(
        std::sync::mpsc::Receiver<ApplyWorkerMsg>,
        std::thread::JoinHandle<()>,
    )> {
        let platform_config = self.platform_config.clone();
        let apply_worker_cancelled = self.apply_worker_cancelled.clone();
        let apply_epoch_ref = self.apply_epoch.clone();
        let apply_epoch = apply_epoch_ref.fetch_add(1, Ordering::SeqCst) + 1;
        let apply_window_ids: Vec<u64> = all_placements.iter().map(|p| p.window_id).collect();
        // Drain the post-animation nudge flag so only the landing pass after
        // an actual scroll / transition fires the (w-1 → w) sticky-compositor
        // nudge. Routine applies skip it, which kills the visible Zen / Slack
        // / Cascadia 1 px wobble that used to fire on every focus shift,
        // drag, or window event.
        let post_animation_nudge = std::mem::take(&mut self.post_animation_nudge_pending);
        #[cfg(test)]
        let injected_behavior = self.injected_apply_placements_behavior.clone();
        #[cfg(test)]
        let injected_apply_placements_call_count =
            self.injected_apply_placements_call_count.clone();
        #[cfg(test)]
        let injected_apply_placements_batches = self.injected_apply_placements_batches.clone();
        #[cfg(test)]
        let late_worker_recovery_count = self.late_worker_recovery_count.clone();

        let (tx, rx) = std::sync::mpsc::channel::<ApplyWorkerMsg>();
        let spawn_result = std::thread::Builder::new()
            .name("leopardwm-apply-layout".to_string())
            .spawn(move || {
                let should_cancel = || {
                    apply_worker_cancelled.load(Ordering::SeqCst)
                        || apply_epoch_ref.load(Ordering::SeqCst) != apply_epoch
                };
                if should_cancel() {
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new(), Vec::new(), Vec::new()));
                    return;
                }

                #[cfg(test)]
                if let Some(behavior) = injected_behavior {
                    let call_index =
                        injected_apply_placements_call_count.fetch_add(1, Ordering::SeqCst);
                    injected_apply_placements_batches
                        .lock()
                        .unwrap()
                        .push(apply_window_ids.clone());
                    let (
                        result,
                        width_violations,
                        height_violations,
                        maximized_skipped_window_ids,
                        landings,
                    ) =
                        match behavior {
                            TestApplyPlacementsBehavior::SleepAndSucceed(delay) => {
                                std::thread::sleep(delay);
                                (Ok(()), Vec::new(), Vec::new(), Vec::new(), Vec::new())
                            }
                            TestApplyPlacementsBehavior::SleepAndFail(delay) => {
                                std::thread::sleep(delay);
                                (
                                    Err(anyhow!("injected apply_placements failure")),
                                    Vec::new(),
                                    Vec::new(),
                                    Vec::new(),
                                    Vec::new(),
                                )
                            }
                            TestApplyPlacementsBehavior::SucceedWithMaximizedSkip(window_id) => {
                                let skipped = if call_index == 0 {
                                    vec![window_id]
                                } else {
                                    Vec::new()
                                };
                                (Ok(()), Vec::new(), Vec::new(), skipped, Vec::new())
                            }
                            TestApplyPlacementsBehavior::SucceedWithSizeViolations(
                                width_violations,
                                height_violations,
                            ) => (
                                Ok(()),
                                width_violations,
                                height_violations,
                                Vec::new(),
                                Vec::new(),
                            ),
                            TestApplyPlacementsBehavior::Scripted(steps) => {
                                let step = steps.get(call_index).cloned().unwrap_or(
                                    TestApplyPlacementsStep {
                                        delay: std::time::Duration::ZERO,
                                        outcome: TestApplyPlacementsOutcome::Succeed {
                                            landings: Vec::new(),
                                        },
                                    },
                                );
                                std::thread::sleep(step.delay);
                                match step.outcome {
                                    TestApplyPlacementsOutcome::Succeed { landings } => {
                                        (Ok(()), Vec::new(), Vec::new(), Vec::new(), landings)
                                    }
                                    TestApplyPlacementsOutcome::SucceedWithFeedback {
                                        width_violations,
                                        height_violations,
                                        landings,
                                    } => (
                                        Ok(()),
                                        width_violations,
                                        height_violations,
                                        Vec::new(),
                                        landings,
                                    ),
                                    TestApplyPlacementsOutcome::Fail => (
                                        Err(anyhow!("injected apply_placements failure")),
                                        Vec::new(),
                                        Vec::new(),
                                        Vec::new(),
                                        Vec::new(),
                                    ),
                                }
                            }
                        };
                    if should_cancel() {
                        run_layout_apply_recovery_pass(
                            &apply_window_ids,
                            "apply-cancelled-late-worker",
                        );
                        #[cfg(test)]
                        late_worker_recovery_count.fetch_add(1, Ordering::SeqCst);
                        let _ = tx.send((Ok(()), Vec::new(), Vec::new(), Vec::new(), Vec::new()));
                        return;
                    }
                    let _ = tx.send((
                        result,
                        width_violations,
                        height_violations,
                        maximized_skipped_window_ids,
                        landings,
                    ));
                    return;
                }

                if should_cancel() {
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new(), Vec::new(), Vec::new()));
                    return;
                }
                let (
                    result,
                    width_violations,
                    height_violations,
                    maximized_skipped_window_ids,
                    landings,
                ) = match leopardwm_platform_win32::apply_placements(
                    &all_placements,
                    &platform_config,
                    None,
                    post_animation_nudge,
                ) {
                    Ok(r) => (
                        Ok(()),
                        r.width_violations,
                        r.height_violations,
                        r.maximized_skipped_window_ids,
                        r.landings,
                    ),
                    Err(e) => (
                        Err(anyhow!(e.to_string())),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                        Vec::new(),
                    ),
                };
                if should_cancel() {
                    run_layout_apply_recovery_pass(
                        &apply_window_ids,
                        "apply-cancelled-late-worker",
                    );
                    #[cfg(test)]
                    late_worker_recovery_count.fetch_add(1, Ordering::SeqCst);
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new(), Vec::new(), Vec::new()));
                    return;
                }
                let _ = tx.send((
                    result,
                    width_violations,
                    height_violations,
                    maximized_skipped_window_ids,
                    landings,
                ));
            });

        match spawn_result {
            Ok(handle) => Ok((rx, handle)),
            Err(e) => {
                self.applying_layout = false;
                Err(anyhow!("Failed to spawn layout worker thread: {}", e))
            }
        }
    }

    fn commit_pending_min_size_clears(&mut self) {
        self.clear_min_size_constraints(|workspace| {
            workspace.commit_pending_min_size_clears();
        });
    }

    pub(crate) fn clear_min_size_constraints(
        &mut self,
        clear: impl Fn(&mut leopardwm_core_layout::Workspace),
    ) {
        let monitor_ids: Vec<_> = self.workspaces.keys().copied().collect();
        let structural_transition_active = self.layout_transition.is_some();
        for monitor_id in monitor_ids {
            let viewport_width = self.viewport_width_for(monitor_id);
            let active_idx = self.active_workspace_idx(monitor_id);
            for (idx, workspace) in self
                .workspaces
                .get_mut(&monitor_id)
                .unwrap()
                .iter_mut()
                .enumerate()
            {
                if idx != active_idx {
                    clear(workspace);
                    continue;
                }
                let before: Vec<_> = effective_column_widths(workspace).collect();
                clear(workspace);
                if !effective_column_widths(workspace).eq(before) {
                    if workspace.is_animating() || structural_transition_active {
                        workspace.ensure_focused_visible_animated(viewport_width);
                    } else {
                        workspace.ensure_focused_visible(viewport_width);
                    }
                }
            }
        }
    }

    /// Feed worker-reported size violations back to the layout engine.
    /// Requests correction for changed effective widths or any accepted height feedback.
    pub(crate) fn propagate_size_violations(
        &mut self,
        width_violations: &[leopardwm_platform_win32::WidthViolation],
        height_violations: &[leopardwm_platform_win32::HeightViolation],
    ) -> bool {
        let mut constraints_changed = false;
        let mut prior_widths = HashMap::new();

        for violation in width_violations {
            let Some((monitor_id, workspace_idx)) = self.find_window_workspace(violation.window_id)
            else {
                continue;
            };
            let usable_width = self
                .workspaces
                .get(&monitor_id)
                .and_then(|workspaces| workspaces.get(workspace_idx))
                .map(|workspace| workspace.visible_width(self.viewport_width_for(monitor_id)))
                .unwrap_or(i32::MAX);
            if violation.min_width >= usable_width {
                debug!(
                    "Ignoring usable-tiled-width violation for window {} ({}px >= {}px usable width)",
                    violation.window_id, violation.min_width, usable_width
                );
                continue;
            }
            if let Some(workspace) = self
                .workspaces
                .get_mut(&monitor_id)
                .and_then(|workspaces| workspaces.get_mut(workspace_idx))
            {
                prior_widths
                    .entry((monitor_id, workspace_idx))
                    .or_insert_with(|| effective_column_widths(workspace).collect::<Vec<_>>());
                workspace.set_window_min_width(violation.window_id, violation.min_width);
            }
        }

        let structural_transition_active = self.layout_transition.is_some();
        for ((monitor_id, workspace_idx), before) in prior_widths {
            let viewport_width = self.viewport_width_for(monitor_id);
            let is_active_workspace = self.active_workspace_idx(monitor_id) == workspace_idx;
            let Some(workspace) = self
                .workspaces
                .get_mut(&monitor_id)
                .and_then(|workspaces| workspaces.get_mut(workspace_idx))
            else {
                continue;
            };
            if effective_column_widths(workspace).eq(before) {
                continue;
            }
            constraints_changed = true;
            if !is_active_workspace {
                continue;
            }
            if workspace.is_animating() || structural_transition_active {
                workspace.ensure_focused_visible_animated(viewport_width);
            } else {
                workspace.ensure_focused_visible(viewport_width);
            }
        }

        for violation in height_violations {
            let Some((monitor_id, workspace_idx)) = self.find_window_workspace(violation.window_id)
            else {
                continue;
            };
            let viewport_height = self
                .monitors
                .get(&monitor_id)
                .map(|monitor| monitor.work_area.height)
                .unwrap_or(i32::MAX);
            if violation.min_height >= viewport_height {
                debug!(
                    "Ignoring viewport-sized height violation for window {} ({}px >= {}px viewport)",
                    violation.window_id, violation.min_height, viewport_height
                );
                continue;
            }
            if let Some(workspace) = self
                .workspaces
                .get_mut(&monitor_id)
                .and_then(|workspaces| workspaces.get_mut(workspace_idx))
            {
                workspace.set_window_min_height(violation.window_id, violation.min_height);
                constraints_changed = true;
            }
        }

        constraints_changed
    }

    /// Post-success bookkeeping: border, tab strip, and deduped LayoutChanged broadcast.
    fn finalize_layout_success(&mut self) {
        if let Some(hwnd) = self.previous_focused_hwnd {
            if self.config.appearance.active_border {
                self.show_border(hwnd);
            }
        }
        // Reposition tab strip overlay (mirror border lifecycle).
        self.update_tab_strip();

        // LayoutChanged broadcast with signature dedup. Animation
        // frames between two settled layouts produce identical
        // signatures so the dedup check suppresses them; only
        // structural changes (column added/removed/reordered, width
        // changed, focus moved between columns) emit.
        let sig = self.focused_layout_signature();
        if self.last_emitted_layout_sig != Some(sig) {
            self.last_emitted_layout_sig = Some(sig);
            let monitor = self.focused_monitor;
            let workspace_index = self.active_workspace_idx(monitor);
            let focused_column = self
                .workspaces
                .get(&monitor)
                .and_then(|list| list.get(workspace_index))
                .map(|ws| ws.focused_column_index());
            self.broadcast_event(leopardwm_ipc::IpcEvent::LayoutChanged {
                monitor: monitor as i64,
                workspace_index: workspace_index as u8,
                focused_column,
                columns: self.focused_layout_columns(),
            });
        }

        // Request a debounced persist if any PERSISTED field changed.
        // Signature dedup + the background debounce coalesce animation
        // frames and rapid structural changes into at most ~one write/sec.
        self.request_save_if_changed();
    }
}

#[cfg(test)]
mod park_tests {
    use crate::physical_placement::offscreen_park_rect;
    use leopardwm_core_layout::Rect;

    // A window scrolled off the owning monitor keeps its size when re-parked.
    const WIN: Rect = Rect {
        x: 6000,
        y: 10,
        width: 800,
        height: 600,
    };

    #[test]
    fn parks_at_the_recoverable_sentinel_with_a_horizontal_neighbor() {
        let owner = Rect::new(0, 0, 5120, 1440);
        let right = Rect::new(5120, 0, 1920, 1080);
        let parked = offscreen_park_rect(WIN, &[owner, right], (0, 0, 0, 0));
        let sentinel = leopardwm_platform_win32::MOVE_OFFSCREEN_SENTINEL_COORD;
        assert_eq!((parked.x, parked.y), (sentinel, sentinel));
        assert_eq!((parked.width, parked.height), (WIN.width, WIN.height));
        assert!(
            ![owner, right].iter().any(|m| parked.intersects(m)),
            "clears every monitor"
        );
    }

    #[test]
    fn parks_at_the_recoverable_sentinel_with_stacked_neighbors() {
        let owner = Rect::new(0, 1080, 1920, 1080);
        let above = Rect::new(0, 0, 1920, 1080);
        let below = Rect::new(0, 2160, 1920, 1080);
        let parked = offscreen_park_rect(WIN, &[owner, above, below], (0, 0, 0, 0));
        let sentinel = leopardwm_platform_win32::MOVE_OFFSCREEN_SENTINEL_COORD;
        assert_eq!((parked.x, parked.y), (sentinel, sentinel));
        assert!(
            ![owner, above, below].iter().any(|m| parked.intersects(m)),
            "clears every monitor"
        );
    }

    #[test]
    fn parks_at_the_recoverable_sentinel_with_three_adjacent_neighbors() {
        let owner = Rect::new(2000, 0, 1000, 1000);
        let below = Rect::new(2000, 1000, 1000, 1000);
        let above = Rect::new(2000, -1000, 1000, 1000);
        let right = Rect::new(3000, 0, 1000, 1000);
        let parked = offscreen_park_rect(WIN, &[owner, below, above, right], (0, 0, 0, 0));
        let sentinel = leopardwm_platform_win32::MOVE_OFFSCREEN_SENTINEL_COORD;
        assert_eq!((parked.x, parked.y), (sentinel, sentinel));
        assert!(
            ![owner, below, above, right]
                .iter()
                .any(|m| parked.intersects(m)),
            "clears every monitor"
        );
    }

    #[test]
    fn falls_back_to_the_far_sentinel_when_boxed_in_on_all_sides() {
        let owner = Rect::new(0, 0, 1000, 1000);
        let neighbors = [
            owner,
            Rect::new(-2000, 0, 2000, 1000), // left
            Rect::new(1000, 0, 2000, 1000),  // right
            Rect::new(0, -2000, 1000, 2000), // above
            Rect::new(0, 1000, 1000, 2000),  // below
        ];
        let parked = offscreen_park_rect(WIN, &neighbors, (0, 0, 0, 0));
        let sentinel = leopardwm_platform_win32::MOVE_OFFSCREEN_SENTINEL_COORD;
        assert_eq!((parked.x, parked.y), (sentinel, sentinel));
    }

    use crate::physical_placement::park_offscreen_avoiding_neighbors;
    use leopardwm_core_layout::{Visibility, WindowPlacement};
    use leopardwm_platform_win32::{MonitorId, MonitorInfo};
    use std::collections::HashMap;

    fn monitor(id: MonitorId, x: i32, y: i32, w: i32, h: i32) -> MonitorInfo {
        MonitorInfo {
            id,
            rect: Rect::new(x, y, w, h),
            work_area: Rect::new(x, y, w, h),
            is_primary: false,
            device_name: String::new(),
            scale_factor: 1.0,
        }
    }

    fn placement(wid: u64, rect: Rect, visibility: Visibility) -> WindowPlacement {
        WindowPlacement {
            window_id: wid,
            rect,
            visibility,
            column_index: 0,
        }
    }

    #[test]
    fn wrapper_reparks_only_bleeding_offscreen_placements() {
        let owner = monitor(1, 0, 0, 5120, 1440);
        let right = monitor(2, 5120, 0, 1920, 1080);
        let monitors: HashMap<MonitorId, MonitorInfo> = [(1, owner.clone()), (2, right.clone())]
            .into_iter()
            .collect();

        let visible = Rect::new(5200, 10, 400, 400); // overlaps neighbor but Visible
        let non_bleed = Rect::new(-500, 10, 400, 400); // off-screen, on owner only
        let bleeding = Rect::new(5300, 10, 400, 400); // off-screen, on neighbor
        let mut placements = vec![
            placement(10, visible, Visibility::Visible),
            placement(20, non_bleed, Visibility::OffScreenLeft),
            placement(30, bleeding, Visibility::OffScreenRight),
        ];

        park_offscreen_avoiding_neighbors(&mut placements, 1, &monitors);

        assert_eq!(placements[0].rect, visible, "visible placement untouched");
        assert_eq!(
            placements[1].rect, non_bleed,
            "non-bleeding off-screen untouched"
        );
        assert_ne!(placements[2].rect, bleeding, "bleeding placement re-parked");
        assert!(
            ![owner.rect, right.rect]
                .iter()
                .any(|m| placements[2].rect.intersects(m)),
            "re-parked clear of every monitor"
        );
    }

    #[test]
    fn wrapper_is_a_no_op_when_the_owner_monitor_is_missing() {
        let right = monitor(2, 5120, 0, 1920, 1080);
        let monitors: HashMap<MonitorId, MonitorInfo> = [(2, right)].into_iter().collect();
        let orig = Rect::new(5300, 10, 400, 400);
        let mut placements = vec![placement(30, orig, Visibility::OffScreenRight)];
        // owner_id 1 isn't in the map -> early return, nothing changes.
        park_offscreen_avoiding_neighbors(&mut placements, 1, &monitors);
        assert_eq!(placements[0].rect, orig);
    }
}
